  spring:
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: airquality-group
        auto-offset-reset: earliest
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.pzprtpvdusqeuxcmkkzj
    password: YourStrong!Passw0rd
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false